config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  resources :almoxarifados
  resources :cargos
  resources :funcionarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cargo.rb
class Cargo < ApplicationRecord
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update, :destroy]

  # GET /cargos
  # GET /cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1
  # GET /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos
  # POST /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Cargo was successfully created.' }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1
  # PATCH/PUT /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: 'Cargo was successfully updated.' }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1
  # DELETE /cargos/1.json
  def destroy
    @cargo.destroy
    respond_to do |format|
      format.html { redirect_to cargos_url, notice: 'Cargo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cargo_params
      params.require(:cargo).permit(:nome)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/views/cargos/_form.html.erb
<%= form_with(model: cargo) do |form| %>
  <% if cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
        <% cargo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h1>Editing Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Show', @cargo %> |
<%= link_to 'Back', cargos_path %>

app/views/cargos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cargos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.nome %></td>
        <td><%= link_to 'Show', cargo %></td>
        <td><%= link_to 'Edit', edit_cargo_path(cargo) %></td>
        <td><%= link_to 'Destroy', cargo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cargo', new_cargo_path %>

app/views/cargos/new.html.erb
<h1>New Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Back', cargos_path %>

app/views/cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cargo.nome %>
</p>

<%= link_to 'Edit', edit_cargo_path(@cargo) %> |
<%= link_to 'Back', cargos_path %>