config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  resources :almoxarifados
  resources :cargos
  resources :funcionarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
        <% departamento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Show', departamento %></td>
        <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
        <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @departamento.nome %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>