config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  resources :almoxarifados
  resources :cargos
  resources :funcionarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/almoxarifado.rb
class Almoxarifado < ApplicationRecord
end

app/controllers/almoxarifados_controller.rb
class AlmoxarifadosController < ApplicationController
  before_action :set_almoxarifado, only: [:show, :edit, :update, :destroy]

  # GET /almoxarifados
  # GET /almoxarifados.json
  def index
    @almoxarifados = Almoxarifado.all
  end

  # GET /almoxarifados/1
  # GET /almoxarifados/1.json
  def show
  end

  # GET /almoxarifados/new
  def new
    @almoxarifado = Almoxarifado.new
  end

  # GET /almoxarifados/1/edit
  def edit
  end

  # POST /almoxarifados
  # POST /almoxarifados.json
  def create
    @almoxarifado = Almoxarifado.new(almoxarifado_params)

    respond_to do |format|
      if @almoxarifado.save
        format.html { redirect_to @almoxarifado, notice: 'Almoxarifado was successfully created.' }
        format.json { render :show, status: :created, location: @almoxarifado }
      else
        format.html { render :new }
        format.json { render json: @almoxarifado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /almoxarifados/1
  # PATCH/PUT /almoxarifados/1.json
  def update
    respond_to do |format|
      if @almoxarifado.update(almoxarifado_params)
        format.html { redirect_to @almoxarifado, notice: 'Almoxarifado was successfully updated.' }
        format.json { render :show, status: :ok, location: @almoxarifado }
      else
        format.html { render :edit }
        format.json { render json: @almoxarifado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /almoxarifados/1
  # DELETE /almoxarifados/1.json
  def destroy
    @almoxarifado.destroy
    respond_to do |format|
      format.html { redirect_to almoxarifados_url, notice: 'Almoxarifado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_almoxarifado
      @almoxarifado = Almoxarifado.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def almoxarifado_params
      params.require(:almoxarifado).permit(:descricao)
    end
end

app/helpers/almoxarifados_helper.rb
module AlmoxarifadosHelper
end

app/views/almoxarifados/_form.html.erb
<%= form_with(model: almoxarifado) do |form| %>
  <% if almoxarifado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(almoxarifado.errors.count, "error") %> prohibited this almoxarifado from being saved:</h2>

      <ul>
        <% almoxarifado.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/almoxarifados/edit.html.erb
<h1>Editing Almoxarifado</h1>

<%= render 'form', almoxarifado: @almoxarifado %>

<%= link_to 'Show', @almoxarifado %> |
<%= link_to 'Back', almoxarifados_path %>

app/views/almoxarifados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Almoxarifados</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @almoxarifados.each do |almoxarifado| %>
      <tr>
        <td><%= almoxarifado.descricao %></td>
        <td><%= link_to 'Show', almoxarifado %></td>
        <td><%= link_to 'Edit', edit_almoxarifado_path(almoxarifado) %></td>
        <td><%= link_to 'Destroy', almoxarifado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Almoxarifado', new_almoxarifado_path %>

app/views/almoxarifados/new.html.erb
<h1>New Almoxarifado</h1>

<%= render 'form', almoxarifado: @almoxarifado %>

<%= link_to 'Back', almoxarifados_path %>

app/views/almoxarifados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @almoxarifado.descricao %>
</p>

<%= link_to 'Edit', edit_almoxarifado_path(@almoxarifado) %> |
<%= link_to 'Back', almoxarifados_path %>